import { Link } from 'react-router-dom';
import { TrendingUp, CheckCircle, Clock, BookOpen, Shield, Zap } from 'lucide-react';

export default function Landing() {
  return (
    <div className="min-h-screen bg-slate-50 dark:bg-background text-slate-900 dark:text-white transition-colors duration-200">
      {/* Navigation */}
      <nav className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 h-20 flex items-center justify-between">
        <div className="flex items-center gap-2 text-primary-600 dark:text-primary-400 font-bold text-2xl tracking-tight">
          <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-primary-500 to-primary-700 flex items-center justify-center text-white shadow-lg shadow-primary-500/20">
            <TrendingUp size={24} />
          </div>
          StudyDash
        </div>
        <div className="flex items-center gap-6">
          <Link to="/login" className="text-sm font-medium hover:text-primary-600 dark:hover:text-primary-400 transition-colors">
            Login
          </Link>
          <Link to="/signup" className="btn-primary py-2 px-5 text-sm">
            Get Started
          </Link>
        </div>
      </nav>

      {/* Hero Section */}
      <main>
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 pt-20 pb-32">
          <div className="text-center space-y-8 animate-slide-up">
            <h1 className="text-5xl md:text-7xl font-extrabold tracking-tight">
              Elevate Your <span className="text-transparent bg-clip-text bg-gradient-to-r from-primary-600 to-primary-400">Academic Journey</span>
            </h1>
            <p className="max-w-2xl mx-auto text-lg md:text-xl text-slate-500 dark:text-slate-400 leading-relaxed">
              The all-in-one productivity dashboard designed for modern students. Track attendance, manage tasks, take notes, and get AI-powered insights.
            </p>
            <div className="flex flex-col sm:flex-row items-center justify-center gap-4 pt-4">
              <Link to="/signup" className="btn-primary py-4 px-8 text-lg w-full sm:w-auto">
                Join Now Free
              </Link>
              <button className="btn-secondary py-4 px-8 text-lg w-full sm:w-auto border border-slate-200 dark:border-slate-800">
                Watch Demo
              </button>
            </div>
          </div>

          {/* Feature Grid */}
          <div className="mt-32 grid grid-cols-1 md:grid-cols-3 gap-8 animate-fade-in">
            <FeatureCard 
              icon={<Zap className="text-yellow-500" />}
              title="AI Assistant"
              description="Get personalized study plans and insights generated by our smart AI engine."
            />
            <FeatureCard 
              icon={<Clock className="text-blue-500" />}
              title="Attendance Tracker"
              description="Never miss a 75% criteria again. Smart calculations and risk alerts."
            />
            <FeatureCard 
              icon={<CheckCircle className="text-green-500" />}
              title="Goal Setting"
              description="Set academic and personal goals. Track your progress with gamified streaks."
            />
          </div>
        </div>
      </main>

      {/* Footer */}
      <footer className="border-t border-slate-200 dark:border-slate-800 py-12">
        <div className="max-w-7xl mx-auto px-4 text-center text-slate-500 dark:text-slate-400 text-sm">
          <p>© 2026 StudyDash. Built for students, by students.</p>
        </div>
      </footer>
    </div>
  );
}

function FeatureCard({ icon, title, description }) {
  return (
    <div className="glass-card p-8 hover:translate-y-[-8px] transition-all duration-300">
      <div className="w-12 h-12 rounded-xl bg-slate-100 dark:bg-slate-800 flex items-center justify-center mb-6">
        {icon}
      </div>
      <h3 className="text-xl font-bold mb-3">{title}</h3>
      <p className="text-slate-500 dark:text-slate-400 leading-relaxed">
        {description}
      </p>
    </div>
  );
}
